# Generated by Django 4.2.16 on 2024-11-14 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0012_2_8'),
        ('accounts', '0002_user_stripe_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account',
            field=models.ForeignKey(blank=True, help_text="The user's Stripe Account object, if it exists", null=True, on_delete=django.db.models.deletion.SET_NULL, to='djstripe.account'),
        ),
    ]
